event/urls.py
from django.conf.urls.defaults import *

from django.views.generic.list_detail import object_detail, object_list
from django.views.generic.simple import direct_to_template
from django.contrib.auth.models import User
from django.contrib.auth.views import login, logout

from views import upload_icon, user_home, claim, tbping, invite, regist, add_comment, cancel, edit_position_paper, upload_document

from models import Event, EventComment, EventTrackback, EventFile

urlpatterns = patterns('',
     (r'^users/home/$', user_home,
             dict(), 'user_home'),
     (r'^users/(?P<username>.*)/upload_icon/$', upload_icon,
             dict(), 'upload_icon'),
     (r'^users/(?P<slug>.*)/$', object_detail,
             dict(queryset=User.objects.filter(is_active=True).exclude(username='admin'),
                  slug_field='username'), 'user_detail'),
     (r'^login/$', login, dict(template_name='login.html'), 'login'),
     (r'^logout/$', logout, dict(next_page='/events/'), 'logout'),
     (r'^invite/$', invite, dict(), 'invite'),
     (r'^invite_email_sent/$', direct_to_template, dict(template='event/invite_mail_sent.html'), 'invite_email_sent'),
     (r'^regist/(?P<activate_key>.*)/$', regist, dict(), 'regist'),
     (r'^(?P<slug>.*)/claim/$', claim, dict(), 'claim'),
     (r'^(?P<slug>.*)/cancel/$', cancel, dict(), 'cancel'),
     (r'^(?P<slug>.*)/tbping/$', tbping, dict(), 'tbping'),
     (r'^(?P<slug>.*)/edit_position_paper/$', edit_position_paper, dict(), 'edit_position_paper'),
     (r'^(?P<slug>.*)/add_comment/$', add_comment, dict(), 'add_comment'),
     (r'^(?P<slug>.*)/upload_document/$', upload_document, dict(), 'upload_document'),
     (r'^(?P<slug>.*)/$', object_detail, dict(queryset=Event.objects.all()), 'event_detail'),
     (r'^$',object_list, dict(queryset=Event.objects.all().order_by('-time_to_start'),
                extra_context={'recent_comment': lambda: EventComment.objects.all().order_by('-id')[:5],
                               'recent_trackback': lambda: EventTrackback.objects.all().order_by('-id')[:5],
                               'recent_document': lambda: EventFile.objects.all().order_by('-id')[:5]
                }), 'event_list'),
)

urls.py
from django.conf.urls.defaults import *
from django.views import static
from django.conf import settings

urlpatterns = patterns('',
    # Example:

    # Uncomment this for admin:
     (r'^admin/', include('django.contrib.admin.urls')),
     (settings.STATIC_REGIX, static.serve, dict(document_root=settings.MEDIR_DIR, show_indexes=True)),
     (r'^events/', include('charmr.event.urls')),
)

event/models.py
from django.conf import settings
from django.db import models
from django.db.models import permalink

from django.contrib.auth.models import User
from django.dispatch import dispatcher
from django.db.models import signals

from django.utils.translation import ugettext as _

from django.contrib.markup.templatetags.markup import restructuredtext

from datetime import datetime

class EventProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    nickname = models.CharField(max_length=30)
    twitter_name = models.CharField(max_length=30, blank=True)
    pownce_name = models.CharField(max_length=30, blank=True)
    blog_url = models.URLField(blank=True)
    icon = models.ImageField('', upload_to='icon', blank=True, null=True)
    
    class Admin:
        pass
    
    def _icon_url(self):
        if self.get_icon_url():
            return settings.MEDIA_URL + '/icon/%s.png' % self.user.username
        return settings.MEDIA_URL + '/icon/anonymous.png'
    icon_url = property(_icon_url)

    def _large_icon_url(self):
        if self.get_icon_url():
            return settings.MEDIA_URL + '/icon/%s' % self.user.username + '_large.png'
        return settings.MEDIA_URL + '/icon/anonymous_large.png'
    large_icon_url = property(_large_icon_url)

class Place(models.Model):
    name = models.CharField(_(u'Place to hold'), max_length=100)
    lat = models.DecimalField(_(u'Latitude'), blank=True, null=True, max_digits=17, decimal_places=14)
    lng = models.DecimalField(_(u'Latitude'), blank=True, null=True, max_digits=17, decimal_places=14)
    link = models.URLField(blank=True)
    address = models.CharField(max_length=200, blank=True)
    tel = models.CharField(max_length=20, blank=True)
    attention = models.CharField(max_length=200, blank=True)

    class Admin:
        list_display = ('name', 'tel', 'attention', )
    
    def __unicode__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(_(u'Event Name'), max_length=100)
    sub_title = models.CharField(_(u'Sub Title'), max_length=100)
    slug = models.SlugField(unique=True)
    time_to_start = models.DateTimeField(_('Event start time'), blank=True, null=True)
    time_to_finish = models.DateTimeField(_('Event finish taime'), blank=True, null=True)
    place = models.ForeignKey(Place)
    max_people = models.IntegerField()
    apply_from = models.DateTimeField(_(u'Date and Time to start applying'), blank=True, null=True)
    apply_to   = models.DateTimeField(_(u'Date and Time to finish applying'), blank=True, null=True)
    pos_paper  = models.TextField(_(u'Position Paper Template'), blank=True)
    owner = models.ForeignKey(User)
    staff = models.ManyToManyField(User, related_name='event_staff', filter_interface=models.HORIZONTAL, limit_choices_to={ 'is_staff': True })
    
    def is_claimable(self):
        """
        >>> e = Event(name='test_name', sub_title='test_sub_title', slug='test_slug', place_id=1, max_people=10, pos_paper = u'')
        >>> e.is_claimable()
        False
        
        >>> from datetime import timedelta
        >>> now = datetime.now()
        >>> e.apply_from = now
        >>> e.is_claimable()
        True
        
        >>> e.apply_to = now + timedelta(hours=1)
        >>> e.is_claimable()
        True
        
        >>> e.apply_from = now + timedelta(minutes=2)
        >>> e.is_claimable()
        False
        
        >>> e.apply_from = now
        >>> e.apply_to = now + timedelta(minutes=-1)
        >>> e.is_claimable()
        False
        
        >>> e.apply_from = now
        >>> e.apply_to = now + timedelta(minutes=1)
        >>> e.time_to_start = now + timedelta(minutes=1)
        >>> e.is_claimable()
        True
        
        >>> e.time_to_start = now + timedelta(minutes=-1)
        >>> e.is_claimable()
        False
        """
        now = datetime.now()
        if not self.apply_from:
            return False
        if now >= self.apply_from and (not self.apply_to or now < self.apply_to):
            if not self.time_to_start or now < self.time_to_start:
                return True
        return False

    class Admin:
        date_hierarchy = 'time_to_start'
        list_display = ('name', 'slug', 'time_to_start', 'apply_from', 'max_people', 'owner', )
        fields = (
            (_(u'Title'), { 'fields': (('name', 'sub_title'),)}),
            (_(u'URL'), { 'fields': ('slug',),}),
            (_(u'Schedule'), { 'fields': ('time_to_start', 'time_to_finish','apply_from', 'apply_to')}),
            (_(u'Info'), { 'fields': ('place', 'max_people', 'pos_paper', 'owner', 'staff',)}),
        )
    
    class Meta:
        ordering = ['id',]
    
    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return ('event_detail', (), { 'slug': self.slug })
    get_absolute_url = permalink(get_absolute_url)
    
    def get_spec_text(self):
        return '\n\n'.join([s.desc for s in self.spec_set.all()])

    def staff_list(self):
        return self.staff.all()
    
    def attendant_list(self):
        att = self.attendant_set.all()
        return att[:self.max_people]
    
    def waiting_list(self):
        att = list(self.attendant_set.all())
        return att[self.max_people:]

class Spec(models.Model):
    event = models.ForeignKey(Event, edit_inline=True)
    sort_order = models.IntegerField()
    desc = models.TextField(_(u'Specification Text'), core=True)

    class Meta:
        ordering = ['sort_order',]
    
class Attendant(models.Model):
    event = models.ForeignKey(Event)
    user  = models.ForeignKey(User)
    pos_paper = models.TextField(blank=True, help_text=_(u'Modify this structured text.'))
    apply_date = models.DateTimeField(editable=False)
    canceled = models.BooleanField(default=False)
    
    class Admin:
        list_display = ('event', 'user', 'canceled', )
    
    class Meta:
        unique_together = (('event', 'user', ), )
        ordering = ['id',]
    
    def save(self):
        if not self.id:
            self.apply_date = datetime.now()
        super(Attendant, self).save()

    
from random import choice

class ActivateKeyManager(models.Manager):
    """
    >>> keys = []
    >>> for i in range(50):
    ...     k = ActivateKey.objects.next().activate_key
    ...     assert k not in keys
    ...     keys.append(k)
    """
    def next(self):
        try:
            key = ''.join([choice('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789') for i in range(50)])
            ActivateKey.objects.get(activate_key__exact=key)
            return self.next()
        except ActivateKey.DoesNotExist:
            act = ActivateKey(activate_key=key, activated=False)
            act.save()
            return act

class ActivateKey(models.Model):
    activate_key = models.CharField(_('Activation Key'), maxlength=50, unique=True)
    activated = models.BooleanField(_('Activate Flag'), default=False)
    email     = models.EmailField(_('Email'))

    objects = ActivateKeyManager()    

    class Admin:
        list_display = ('email', 'activated', )
        list_filter = ('activated',)

class EventComment(models.Model):
    event = models.ForeignKey(Event)
    user = models.ForeignKey(User)
    date = models.DateTimeField(blank=True)
    comment = models.TextField(max_length=3000)
    
    class Admin:pass

    class Meta:
        ordering = ['-id',]

    def save(self):
        if not self.id:
            self.date = datetime.now()
        super(EventComment, self).save()

class EventTrackback(models.Model):
    event = models.ForeignKey(Event)
    date = models.DateTimeField(blank=True)
    blog_name = models.CharField(maxlength=200, blank=True)
    url = models.URLField(blank=False, verify_exists=False)
    excerpt = models.TextField(blank=False)
    
    class Admin:pass

    class Meta:
        ordering = ['-id',]
    
    def save(self):
        if not self.id:
            self.date = datetime.now()
        super(EventTrackback, self).save()


class EventFile(models.Model):
    event = models.ForeignKey(Event)
    user  = models.ForeignKey(User)
    date = models.DateTimeField(blank=True, editable=False)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    document = models.FileField(upload_to=settings.MEDIA_SUFFIX + '/document/%Y/%m/%d')

    class Admin:pass

    class Meta:
        ordering = ['id',]
    
    def save(self):
        if not self.id:
            self.date = datetime.now()
        super(EventFile, self).save()

def add_user_call_back(signal, sender, instance, **kwags):
    """
    >>> from django.contrib.auth.models import User
    >>> u = User.objects.create_user('testuser', 'test@everes.net', password='password')
    >>> profile = u.get_profile()
    >>> profile.nickname
    u'testuser'
    """
    try:
        instance.get_profile()
    except EventProfile.DoesNotExist:
        profile = EventProfile()
        profile.user = instance
        profile.nickname = instance.username
        profile.save()

dispatcher.connect(
    receiver = add_user_call_back,
    signal   = signals.post_save,
    sender   = User
)

event/forms.py
# -*- coding: utf-8 -*-
from django import newforms as forms
from django.contrib.auth.models import User

from django.conf import settings

import re

class InviteForm(forms.Form):
    email = forms.EmailField(label=_('Email'))

class RegistForm(forms.Form):
    username = forms.CharField(label=_('Username'), min_length=4, max_length=30)
    password1 = forms.CharField(label=_('Password'), min_length=6, max_length=60, widget=forms.PasswordInput)
    password2 = forms.CharField(label=_('Confirm Passowrd'), min_length=6, max_length=60, widget=forms.PasswordInput)
    
    
    def clean_username(self):
        value = self.cleaned_data.get('username')
        if not alnum_re.search(value):
            raise forms.ValidationError, _(u"This value must contain only letters, numbers and underscores.")
        ng = [u for u in settings.NG_USERNAME if u in value.lower()]
        if ng:
            raise forms.ValidationError, _(u"You can't use this username(prohibited).")
        try:
            User.objects.get(username__iexact=value)
            raise forms.ValidationError, _(u"Username already taken.")
        except User.DoesNotExist:
            return self.cleaned_data.get('username')
    
    def clean_password2(self):
        p1 = self.cleaned_data.get('password1')
        p2 = self.cleaned_data.get('password2')
        if not (p1 == p2):
            raise forms.ValidationError, _(u"Confirm password.")
        return p2

    def save(self):
        user = User.objects.create_user(self.cleaned_data.get('username'), '', self.cleaned_data.get('password1'))
        return user

def clean_icon(self, value):
    if 'content-type' in value:  
        main, sub = value['content-type'].split('/')  
        if not (main == 'image' and sub in ['jpeg', 'gif', 'png']):  
            raise forms.ValidationError(_('JPEG, PNG, GIF only.'))  
    return value  

alnum_re = re.compile(r'^\w+$')

def isAlphaNumeric(field_data, all_data):
    """
    >>> var = 'ascii_123a'
    >>> isAlphaNumeric(var, None)
    """
    if not alnum_re.search(field_data):
        raise ValidationError, _(u"This value must contain only letters, numbers and underscores.")

event/templates/event/add_comment.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Add Comment' %} | {{ object.name|escape }}{% endblock title %}

{% block main %}
  <div class="section">
    <h2>{% trans 'Post Your Comment to' %} {{ object.name|escape }}</h2>
    <h3>※ 登録したデータは、将来 http://www.djangoproject.jp/ へ移行される予定です。</h3>
    {% if preview_data %}
    <div class="section">
      <h3>{% trans 'Preview' %}</h3>
      <div class="user_action">
        {{ preview_data|escape|urlize|linebreaksbr }}
        <form method="POST">
          <input type="hidden" name="mode" value="post" />
          <input type="hidden" name="comment" value="{{ preview_data|escape }}" />
          <input type="submit" value="{% trans 'Post comment' %}" />
        </form>
      </div>
    </div>
    {% endif %}
    <div class="user_action">
        <form method="POST">
          <table>
            <input type="hidden" name="mode" value="preview" />
            {{ form.comment }}
          </table>
            <input type="submit" value="{% trans 'Preview Comment' %}" />
        </form>
    </div>
  </div>
{% endblock %}

event/templates/event/base.html
{% extends 'base.html' %}

event/templates/event/cancel_confirm.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Cancel?' %} | {{ object.name|escape }}{% endblock title %}

{% block main %}
  <div class="section">
    <h2>{% trans 'Are you sure to cancel your claim?' %}</h2>
    <div class="user_action">
        <form method="POST">
            <input type="submit" value="{% trans 'Cancel' %}" />
        </form>
    </div>
  </div>
{% endblock %}

event/templates/event/claim.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Claim' %} {{ object.name|escape }}{% endblock title %}

{% block overview %}
		<h1><a href=".">{{ object.name|escape }}</a></h1>
		<h2>{% trans 'Claim' %}</h2>
{% endblock overview %}

{% block main %}
  <div class="section">
    <div class="section>
        <h2><a href=".">{{ object.name|escape }}</a></h2>
        <h2><a href=".">{{ object.sub_title|escape }}</a></h2>
        <h3>
            開催日時: {% if object.time_to_start %}{{ object.time_to_start|date:"Y/m/d" }} {{ object.time_to_start|date:"A g:i" }} 〜 {% else %}未定{% endif %}
            {% if object.time_to_finish %} {{ object.time_to_finish|date:"Y/m/d" }} {{ object.time_to_finish|date:"A g:i" }}{% else %}未定{% endif %}
        </h3>
        <h3>
            受付期間: {% if object.apply_from %}{{ object.apply_from|date:"Y/m/d" }} {{ object.apply_from|date:"A g:i" }} 〜 {% else %}未定{% endif %}
            {% if object.apply_to %}{{ object.apply_to|date:"Y/m/d" }} {{ object.apply_to|date:"A g:i" }}{% else %}未定{% endif %}
        </h3>
    </div>
    <div class="user_action">
        <h2>{% trans 'Claim' %}</h2>
        <form method="POST">
          <table>
          {{ form }}
          </table>
          <input type="submit" value="{% trans 'Claim!' %}" />
        </form>
    </div>
  </div>
{% endblock %}

event/templates/event/edit_position_paper.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Edit Position Paper' %} | {{ object.name|escape }}{% endblock title %}

{% block main %}
  <div class="section">
    <h2>{% trans 'Edit Your Position Paper.' %} ({{ object.name|escape }})</h2>
    <h3>※ 登録したデータは、将来 http://www.djangoproject.jp/ へ移行される予定です。</h3>
    <div class="user_action">
        <form method="POST">
          <table>
            {{ form }}
          </table>
            <input type="submit" value="{% trans 'Update Position Paper' %}" />
        </form>
    </div>
  </div>
{% endblock %}

event/templates/event/event_detail.html
{% extends 'event/base.html' %}
{% load i18n %}
{% load markup %}

{% block title %}{{ object.name|escape }}{% endblock title %}

{% block overview %}
		<h1><a href=".">{{ object.name|escape }}</a></h1>
		<h2><a href=".">{{ object.sub_title|escape }}</a></h2>
{% endblock overview %}

{% block updates %}
		<div id="updates" class="boxed">
                    <h2 class="title">{% trans 'Comments' %}</h2>
                    <div class="content">
                        <ul>
                    {% if object.eventcomment_set.all %}
                        {% for comment in object.eventcomment_set.all %}
                            <li><h3>{{ comment.date|date:"Y/m/d" }} {{ comment.date|date:"A g:i" }} by <a href="{% url user_detail comment.user.username %}">{{ comment.user.get_profile.nickname|escape }}</a></h3>
                                <p>{{ comment.comment|escape }}</p></li>
                        {% endfor %}
                    {% else %}
                        <li>{% trans "No Comments yet." %}</li>
                    {% endif %}
                        </ul>
                    {% if user.is_authenticated %}
                        <div class="action">
                            <a href="{% url add_comment object.slug %}">{% trans 'Add Comment' %}</a>
                        </div>
                    {% endif %}
                    </div>

                    <h2 class="title">{% trans 'Documents' %}</h2>
                    <div class="content">
                        <ul>
                    {% if object.eventfile_set.all %}
                        {% for file in object.eventfile_set.all %}
                            <li><h3>{{ file.date|date:"Y/m/d" }} {{ file.date|date:"A g:i" }} by <a href="{% url user_detail comment.user.username %}">{{ file.user.get_profile.nickname|escape }}</a></h3>
                                <p><a href="{{ file.get_document_url }}">{{ file.title|escape }}</a></p>
                                <p>{{ file.description|escape|linebreaksbr }}</p>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li>{% trans "No Documents yet." %}</li>
                    {% endif %}
                        </ul>
                    {% if user.is_authenticated %}
                        <div class="action">
                            <a href="{% url upload_document object.slug %}">{% trans 'Upload Document' %}</a>
                        </div>
                    {% endif %}
                    </div>

                    <h2 class="title">{% trans 'Trackbacks' %}</h2>
                    <div class="content">
                        <ul>
                    {% if object.eventtrackback_set.all %}
                        {% for trackback in object.eventtrackback_set.all %}
                            <li><h3><a href="{{ trackback.url }}" rel="nofollow">{{ trackback.blog_name|escape }}</a> {{ trackback.date|date:"Y/m/d" }} {{ trackback.date|date:"A g:i" }}</h3>
                                <p>{{ trackback.excerpt|escape }}</p></li>
                        {% endfor %}
                    {% else %}
                        <li>{% trans "No Trackbacks yet." %}</li>
                    {% endif %}
                        </ul>
                        <br />
                        <p>{% trans "send trackback to" %} <br /><a href="{% url tbping object.slug %}">{% url tbping object.slug %}</a></p>
                    </div>
                </div>
{% endblock %}

{% block main %}
      {% include 'snippet/claim_snippet.html' %}

      <div class="section">
        <h2>開催概要</h2>
        <table class="information">
          <tr>
            <th>タイトル</th>
            <td>{{ object.name|escape }} (<small>{{ object.sub_title|escape }}</small>)</td>
          </tr>
          <tr>
            <th>開催日時: </th>
            <td>
                {% if object.time_to_start %}{{ object.time_to_start|date:"Y/m/d" }} {{ object.time_to_start|date:"A g:i" }} 〜 {% else %}未定{% endif %}
                {% if object.time_to_finish %}{{ object.time_to_finish|date:"Y/m/d" }} {{ object.time_to_finish|date:"A g:i" }}{% else %}未定{% endif %}
            </td>
          </tr>
          <tr>
            <th>受付期間: </th>
            <td>
                {% if object.apply_from %}{{ object.apply_from|date:"Y/m/d" }} {{ object.apply_from|date:"A g:i" }} 〜 {% else %}未定{% endif %}
                {% if object.apply_to %}{{ object.apply_to|date:"Y/m/d" }} {{ object.apply_to|date:"A g:i" }}{% else %}未定{% endif %}
            </td>
          </tr>
          <tr>
            <th>募集人数: </th>
            <td>
                {{ object.max_people }}人
            </td>
          </tr>
          <tr>
            <th>開催場所: </th><td><a href="{{ object.place.link }}">{{ object.place.name }}</a></td>
          </tr>
          <tr>
            <th>住所：</th><td>{{ object.place.address }}</td>
          </tr>
          <tr>
            <th>電話：</th><td>{{ object.place.tel }}</td>
          </tr>
          <tr>
            <th>注意事項：</th><td>{{ object.place.attention }}</td>
          </tr>
        </table>
      </div>
      

      {{ object.get_spec_text|restructuredtext }}
      
      {% for attendant in object.attendant_list %}
      {% if forloop.first %}
      <div class="section">
        <div class="attendant">
          <h2>{% trans "Attendant" %}</h2>
          <table>
        {% endif %}
          <tr class="{% cycle odd,even %}">
            <th>
                  <img src="{{ attendant.user.get_profile.icon_url }}" clas="thumb_icon" /><br />
                  <a href="{% url user_detail attendant.user.username %}">{{ attendant.user.get_profile.nickname|escape }}</a>
                  {% ifequal attendant.user.id user.id %}
                    <p class="action"><a href="{% url cancel object.slug %}">{% trans 'Cancel' %}</a></p>
                    <p class="action"><a href="{% url edit_position_paper object.slug %}">{% trans 'Edit' %}</a></p>
                  {% endifequal %}
            </th>
            <td>{{ attendant.pos_paper|escape|urlize|linebreaksbr }}</td>
          </tr>
        {% if forloop.last %}
          </table>
        </div>
      </div>
        {% endif %}
      {% endfor %}
      
      {% for waiting in object.waiting_list %}
      {% if forloop.first %}
      <div class="section">
        <div class="waiting">
          <h2>{% trans "Waiting People" %}</h2>
          <table>
        {% endif %}
          <tr class="{% cycle odd,even %}">
            <th><a href="{% url user_detail waiting.user.username %}">
                  <img src="{{ waiting.user.get_profile.icon_url }}" /><br />
                  {{ waiting.user.get_profile.nickname|escape }}</a>
                  {% ifequal waiting.user.id user.id %}
                    <p class="action"><a href="{% url cancel object.slug %}">{% trans 'Cancel' %}</a></p>
                    <p class="action"><a href="{% url edit_position_paper object.slug %}">{% trans 'Edit' %}</a></p>
                  {% endifequal %}
            </th>
            <td>{{ waiting.pos_paper|escape|urlize|linebreaksbr }}</td>
          </tr>
        {% if forloop.last %}
          </table>
        </div>
      </div>
      {% endif %}
      {% endfor %}

      {% include 'snippet/claim_snippet.html' %}

      {% for staff in object.staff.all %}
      {% if forloop.first %}
      <div class="staff">
        <h2>{% trans "Staff" %}</h2>
        <ul>
      {% endif %}
          <li><a href="{% url user_detail staff.username %}">{{ staff.get_profile.nickname|escape }}</a></li>
      {% if forloop.last %}
        </ul>
      </div>
      {% endif %}
      {% endfor %}

{% endblock %}

event/templates/event/invite.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Invite to Django Event Site.' %}{% endblock title %}

{% block main %}
  <div class="section">
    <h2>{% trans 'Are you sure to invite yourself to Django-Event?' %}</h2>
    <h3>※ 登録したデータは、将来 http://www.djangoproject.jp/ へ移行される予定です。</h3>
    <div class="user_action">
        <form method="POST">
          <fieldset>
            <label for="id_email">{% trans 'Email' %}:</label><br />
            {{ form.email }}<input type="submit" value="{% trans 'Invite me!' %}" />
          </fieldset>
        </form>
    </div>
  </div>
{% endblock %}

event/templates/event/invite_mail_sent.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Check Your Mail box' %}{% endblock title %}

{% block main %}
<div class="section">
    <div class="error">
        <h3>{% trans 'Invitation email was sent. Check Your Mail box' %}</h3>
    </div>
</div>
{% endblock %}

event/templates/event/regist.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Regist' %}{% endblock title %}

{% block main %}
  <div class="section">
    <h2>{% trans 'Are you sure to regist yourself to Django-Event?' %}</h2>
    <h3>※ 登録したデータは、将来 http://www.djangoproject.jp/ へ移行される予定です。</h3>
    <div class="user_action">
        <form method="POST">
          <table>
            {{ form }}
          </table>
            <input type="submit" value="{% trans 'Regist me!' %}" />
        </form>
    </div>
  </div>
{% endblock %}

event/templates/event/upload_document.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Upload Document' %} | {{ object.name|escape }}{% endblock title %}

{% block main %}
  <div class="section">
    <h2>{% trans 'Upload document.' %} ({{ object.name|escape }})</h2>
    <h3>※ 登録したデータは、将来 http://www.djangoproject.jp/ へ移行される予定です。</h3>
    <div class="user_action">
        <form enctype="multipart/form-data" method="POST">
          <table>
            {{ form }}
          </table>
            <input type="submit" value="{% trans 'Upload document' %}" />
        </form>
    </div>
  </div>
{% endblock %}